spring.application.name=Pagination_demo
spring.datasource.url=jdbc:mysql://database-2.cd8s4y4yod56.ap-south-2.rds.amazonaws.com:3306/spring
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
